### ISSUE TITLE
magicaxis no longer on CRAN

### ISSUE THREAD

**Issue by kateharborne** [ICRAR/ProFit#12]
As `magicaxis` is no longer a CRAN package, ProFit will not install successfully. 

```
install_github("ICRAR/ProFit@master") 
>>  [...]
>>  * magicaxis: Can't find package called magicaxis.
>>  * ICRAR/ProFit@master: Can't install dependency magicaxis (>= 2.0.3)
```

Requires an edit to DESCRIPTION to point to GitHub version:

```
Remotes:
   asgr/magicaxis@master
```

**Comment by rtobar** [comment]
Since this is affecting both Rfits and Profit already, maybe the way to go is to re-instate magicaxis in CRAN to begin with! Aaron is away this week, but I'll check with him if that's on his radar.

**Comment by asgr** [comment]
All good now- magicaxis is back on CRAN!
